# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame

class Ui_frame(QFrame):
    def __init__(self):
        super ().__init__ ()
        # self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)  # 只显示关闭按钮
        self.setupUi (self)  # 初始化窗体设置
    def setupUi(self, frame):
        frame.setObjectName("frame")
        frame.setEnabled(True)
        frame.resize(433, 383)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icon_math01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frame.setWindowIcon(icon)
        frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayoutWidget = QtWidgets.QWidget(frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 391, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_num1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_num1.setMouseTracking(False)
        self.lineEdit_num1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num1.setDragEnabled(True)
        self.lineEdit_num1.setObjectName("lineEdit_num1")
        self.horizontalLayout.addWidget(self.lineEdit_num1)
        self.label_add = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_add.setFont(font)
        self.label_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_add.setAutoFillBackground(True)
        self.label_add.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add.setObjectName("label_add")
        self.horizontalLayout.addWidget(self.label_add)
        self.lineEdit_num2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_num2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num2.setObjectName("lineEdit_num2")
        self.horizontalLayout.addWidget(self.lineEdit_num2)
        self.label_equal = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_equal.setFont(font)
        self.label_equal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_equal.setAutoFillBackground(True)
        self.label_equal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_equal.setObjectName("label_equal")
        self.horizontalLayout.addWidget(self.label_equal)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 130, 391, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_num21 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_num21.setMouseTracking(False)
        self.lineEdit_num21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num21.setDragEnabled(True)
        self.lineEdit_num21.setObjectName("lineEdit_num21")
        self.horizontalLayout_2.addWidget(self.lineEdit_num21)
        self.label_add_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_add_2.setFont(font)
        self.label_add_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_add_2.setAutoFillBackground(True)
        self.label_add_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_2.setObjectName("label_add_2")
        self.horizontalLayout_2.addWidget(self.label_add_2)
        self.lineEdit_num22 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_num22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num22.setObjectName("lineEdit_num22")
        self.horizontalLayout_2.addWidget(self.lineEdit_num22)
        self.label_equal_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_equal_2.setFont(font)
        self.label_equal_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_equal_2.setAutoFillBackground(True)
        self.label_equal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_equal_2.setObjectName("label_equal_2")
        self.horizontalLayout_2.addWidget(self.label_equal_2)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 290, 391, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_num41 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_num41.setMouseTracking(False)
        self.lineEdit_num41.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num41.setDragEnabled(True)
        self.lineEdit_num41.setObjectName("lineEdit_num41")
        self.horizontalLayout_3.addWidget(self.lineEdit_num41)
        self.label_add_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_add_3.setFont(font)
        self.label_add_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_add_3.setAutoFillBackground(True)
        self.label_add_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_3.setObjectName("label_add_3")
        self.horizontalLayout_3.addWidget(self.label_add_3)
        self.lineEdit_num42 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_num42.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num42.setObjectName("lineEdit_num42")
        self.horizontalLayout_3.addWidget(self.lineEdit_num42)
        self.label_equal_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_equal_3.setFont(font)
        self.label_equal_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_equal_3.setAutoFillBackground(True)
        self.label_equal_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_equal_3.setObjectName("label_equal_3")
        self.horizontalLayout_3.addWidget(self.label_equal_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 210, 391, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_num31 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_num31.setMouseTracking(False)
        self.lineEdit_num31.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num31.setDragEnabled(True)
        self.lineEdit_num31.setObjectName("lineEdit_num31")
        self.horizontalLayout_4.addWidget(self.lineEdit_num31)
        self.label_add_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_add_4.setFont(font)
        self.label_add_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_add_4.setAutoFillBackground(True)
        self.label_add_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_4.setObjectName("label_add_4")
        self.horizontalLayout_4.addWidget(self.label_add_4)
        self.lineEdit_num32 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_num32.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num32.setObjectName("lineEdit_num32")
        self.horizontalLayout_4.addWidget(self.lineEdit_num32)
        self.label_equal_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_equal_4.setFont(font)
        self.label_equal_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_equal_4.setAutoFillBackground(True)
        self.label_equal_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_equal_4.setObjectName("label_equal_4")
        self.horizontalLayout_4.addWidget(self.label_equal_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(frame)
        self.pushButton.setGeometry(QtCore.QRect(360, 20, 61, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(frame)
        QtCore.QMetaObject.connectSlotsByName(frame)

    def retranslateUi(self, frame):
        _translate = QtCore.QCoreApplication.translate
        frame.setWindowTitle(_translate("frame", "加减乘除"))
        self.label_add.setText(_translate("frame", "+"))
        self.label_equal.setText(_translate("frame", "="))
        self.label.setText(_translate("frame", "answer01"))
        self.label_add_2.setText(_translate("frame", "-"))
        self.label_equal_2.setText(_translate("frame", "="))
        self.label_2.setText(_translate("frame", "answer02"))
        self.label_add_3.setText(_translate("frame", "/"))
        self.label_equal_3.setText(_translate("frame", "="))
        self.label_4.setText(_translate("frame", "answer04"))
        self.label_add_4.setText(_translate("frame", "X"))
        self.label_equal_4.setText(_translate("frame", "="))
        self.label_3.setText(_translate("frame", "answer03"))
        self.pushButton.setText(_translate("frame", "开始计算"))
        self.pushButton.clicked.connect(self.startCount)
        self.answer=''

    def startCount(self):
        if self.sender()==self.pushButton:
            self.answer = str(int(self.lineEdit_num1.text())+int(self.lineEdit_num2.text()))
            self.label.setText(self.answer)
